### ISSUE TITLE
User API v2 Documentation

### ISSUE THREAD

**Issue by ChrisMcLain** [edlink/docs#2]
- Middleware Guides
    * [x] Errors & Warnings `errors-warnings.md`
    * [x] Idempotency Keys `idempotency.md`
    * [x] $fields `limiting-fields.md`
    * [x] $properties (for PATCH requests) `patch-requests.md`
    * [x] $expand `expanding-results.md`
    * [x] cursor pagination `paginated-requests.md`
- Glossaries
    * [x] Errors
    * [x] Warnings
- Update External Models
    * [x] assignment
    * [x] submission
    * [x] category
- User API v2 Endpoints
    * [x] agents
    * [x] classes 
    * [x] categories
    * [x] assignments
    * [x] submissions
    * [x] districts
    * [x] profile
    * [x] schools
    * [x] sections
    * [x] enrollments

**Comment by DakotaG** [comment]
Reminder to update the migration guide from 1.0 to include migrating assignments, etc.
